---
- debug:
    msg: "Run fabiohbarbosa.docker role for users: {{item}}"
  with_items: '{{docker_users}}'

- name: 'Check distribution compatibility'
  fail: msg="Role not compatibility with {{ ansible_distribution }} distribuition"
  when: ansible_distribution != 'Ubuntu'

- name: 'Check Ubuntu release compatibility'
  fail: msg="Role not compatibility with {{ ansible_distribution_release }}"
  when: ansible_distribution_release != 'trusty' and ansible_distribution_release != 'xenial' and ansible_distribution_release != 'yakkety' and ansible_distribution_release != 'zesty'

- name: Uninstall old versions
  apt: name={{item}} state=absent
  with_items:
    - docker
    - docker-engine

- name: Update apt packages
  apt: update_cache=true

- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker official GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  when: ansible_distribution_release == 'zesty'

- name: Add docker stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial' or ansible_distribution_release == 'yakkety'

- name: Update apt packages
  apt: update_cache=true

- name: Install docker-ce
  apt: name=docker-ce state=latest

- name: Add users to docker group
  shell: usermod -aG docker {{item}}
  with_items: '{{docker_users}}'

- name: Restart docker daemon service
  service:
    name: docker
    state: restarted