---
- debug:
    msg: 
      - "***********************************************************************"
      - "Running fabiohbarbosa.docker role for {{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }}"
      - "***********************************************************************"

- include: compatibility.yml

- include: docker.yml
  become: yes

- include: compose.yml
  become: yes